INSERT INTO Pizzas
    (Nombre, Descripcion, Precio, Ingredientes, FechaCreacion, ImagenUrl)
VALUES
(
    'Muzzarella',
    'La clásica pizza argentina con salsa de tomate, muzzarella y orégano.',
    8500.00,
    '["Salsa de tomate", "Muzzarella", "Orégano"]',
    UTC_TIMESTAMP(),
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiv6PvL2gD48msLbXb4J7H66gtlEZXRz_hoiusv8_Iauzfqrf--5AyHMqr&s=10'
),
(
    'Napolitana',
    'Pizza con muzzarella, rodajas de tomate y orégano.',
    9500.00,
    '["Salsa de tomate", "Muzzarella", "Tomate", "Orégano"]',
    UTC_TIMESTAMP(),
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTIdLIoB8enL1kftBxlu5wP35taYZpdKOTnMASgWz6ntAKQgW8SenPcZA&s=10'
),
(
    'Jamón y Morrones',
    'Pizza con muzzarella, jamón y morrones.',
    10500.00,
    '["Salsa de tomate", "Muzzarella", "Jamón", "Morrones"]',
    UTC_TIMESTAMP(),
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzOE0BX7CQJyfwzEhmeyX-V4XaWm_ieQDrJ9jOBH-JX4E0nBXagjNumlh4&s=10'
),
(
    'Fugazzeta',
    'Pizza con abundante muzzarella, cebolla y orégano.',
    11000.00,
    '["Muzzarella", "Cebolla", "Orégano"]',
    UTC_TIMESTAMP(),
    'https://latorrepizza.com.ar/wp-content/uploads/2023/05/fugazzeta-con-jamon.png'
),
(
    'Calabresa',
    'Pizza con muzzarella, longaniza calabresa y orégano.',
    11500.00,
    '["Salsa de tomate", "Muzzarella", "Longaniza calabresa", "Orégano"]',
    UTC_TIMESTAMP(),
    'https://img.magnific.com/psd-gratis/deliciosa-pizza-pepperoni-es-delicia-culinaria_632498-24206.jpg?semt=ais_hybrid&w=740&q=80'
),
(
    'Tomate con Albahaca',
    'Pizza con tomate, muzzarella y albahaca fresca.',
    12000.00,
    '["Tomate", "Muzzarella", "Albahaca"]',
    UTC_TIMESTAMP(),
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdhRuSkQ6cppQwCb2CSJ1Ty3HuGQWW9g3VWdxpi5L9Iw&s=10'
);